language: cpp

script:
# Only the clang(-3.4) package provide /usr/bin/clang, but this path is hardcoded in icecream.
# So for now make icecream use this newer version.
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo ln -s /usr/bin/clang-3.9 /usr/bin/clang; sudo ln -s /usr/bin/clang++-3.9 /usr/bin/clang++; export LLVM_CONFIG=/usr/bin/llvm-config-3.9; fi
  - ./autogen.sh
  - ./configure --prefix=$PWD/_inst
  - make
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then make test-strict; fi

matrix:
  include:
  - os: linux
    sudo: true # for setcap so we can run the tests in chroot.
    compiler: gcc
    dist: trusty
  - os: linux
    sudo: true # for setcap so we can run the tests in chroot.
    compiler: clang
    dist: trusty
  - os: linux
    sudo: true # for setcap so we can run the tests in chroot.
    compiler: clang
    env: BUILD_TYPE=asan
    dist: trusty
  - os: linux
    sudo: true # for setcap so we can run the tests in chroot.
    compiler: clang
    env: BUILD_TYPE=lsan
    dist: trusty
  - os: linux
    sudo: true # for setcap so we can run the tests in chroot.
    compiler: clang
    env: BUILD_TYPE=ubsan
    dist: trusty
  - os: osx
    before_install:
      - brew update
      - brew install lzo docbook2x
  allow_failures:
  - compiler: clang
    env: BUILD_TYPE=lsan

before_script:
  - |
     if [ "$BUILD_TYPE" == "asan" ]; then
         export SAN_FLAGS="-fsanitize=address -fno-omit-frame-pointer"
     fi
  - |
     if [ "$BUILD_TYPE" == "lsan" ]; then
         export SAN_FLAGS="-fsanitize=leak -fno-omit-frame-pointer"
     fi
  - |
     if [ "$BUILD_TYPE" == "msan" ]; then
         export SAN_FLAGS="-fsanitize=memory-fno-omit-frame-pointer"
     fi
  - |
     if [ "$BUILD_TYPE" == "ubsan" ]; then
         export SAN_FLAGS="-fsanitize=undefined -fno-omit-frame-pointer"
         export LDFLAGS="$UBSAN_FLAGS ${LDFLAGS}"
         export UBSAN_OPTIONS=print_stacktrace=1
     fi
  - |
      export CFLAGS="${SAN_FLAGS} ${CFLAGS} -Wall -Wextra"
      export CXXFLAGS="${SAN_FLAGS} ${CXXFLAGS} -Wall -Wextra"
      export LDFLAGS="${SAN_FLAGS} ${LDFLAGS}"


addons:
  apt:
    packages:
    - clang-3.9
    - libclang-3.9-dev
    - llvm-3.9-dev
    - libcap-ng-dev
    - libcap-ng-utils
    - liblzo2-dev
    - docbook2x
    - realpath
    - gdb
